# Generated by Django 5.1.1 on 2024-10-25 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=20, null=True)),
                ('color_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'Xlarge')], max_length=3, null=True)),
                ('inventory', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_SKU',
        ),
        migrations.AlterModelManagers(
            name='customers',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='sells',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='count',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='mainproject.customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.IntegerField(choices=[(0, 'Alexanderia'), (1, 'Cairo')], null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ordeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='mainproject.orders'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='mainproject.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dateOfDelivery',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dateOfOrder',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_delevered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainproject.customers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sells',
            name='ordeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaces', to='mainproject.orders'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='mainproject.sellerpref'),
        ),
        migrations.AddField(
            model_name='product_color',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mainproject.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='varientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainproject.product_color'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='varientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='mainproject.product_color'),
        ),
    ]
