# Generated by Django 5.1.1 on 2024-10-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
